---
- hosts: 172.31.29.142
  become: yes
  gather_facts: yes
  tasks:
  - name: execute linux commands
    command: hostname -f
    register: myfirsttaskresult


  - name: i want to get the first task result
    debug: 
      msg: "{{myfirsttaskresult}}"

