---
- hosts: 172.31.29.142
  become: true
  gather_facts: yes
  tasks:
  - include_tasks: myfile.yml
  
  - name: i want to copy file from ansible master to node
    copy:
        src: mystatic
        dest: /home/ubuntu/mystaticfile

  - name: i want to install webserver
    apt:
        name: apache2
        state: present

  - name: i want to copy dynamic file from ansible master to node
    template:
        src: myindexfile.j2
        dest: /var/www/html/index.html


  - name: Download file and force basic auth
    get_url:
        url: http://example.com/path/file.conf
        dest: /home/ubuntu/testfile
        force_basic_auth: yes