---
- hosts: all
  become: true
  gather_facts: yes
  tasks:
  - name: i want to uninstall webserver
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: i want to start webserver
    apt:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
