---
- hosts: mywebservers
  become: true
  gather_facts: yes
  tasks:
  - name: i want to uninstall webserver
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
  - name: i want to uninstall webserver
    yum:
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"
  
 
