---
- hosts: all
  become: true
  tasks:
  - name: Install webserver
    apt:
      name: apache2
      state: absent
  - name: i want to start webserver
    service:
      name: apache2
      state: started
